http://localhost:5001/posts

### 

POST  http://localhost:5001/posts
Content-Type: application/json 

{
    "title": "My book towards Success",
    "content": "The main focus is to find what you want to do and how you would like to do plays a crucial role in our life always be focus and attentive for everything",
    "author": "Raj Reddy"
}

###
PUT http://localhost:5001/posts/1 
Content-Type: application/json

{
    "title" : "My book towards Success",
    "content": "The main focus is to find what you want to do and how you would like to do plays a crucial role in our life always be focus and attentive for everything",
    "author": "Mr. Rahul Reddy"
}